name: Portfolio Deploy 
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: NPM Cleaning
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm package-lock.json
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
